FROM python:3.8
ENV PYTHONUNBUFFERED 1


COPY ./requirements.txt /requirements.txt
RUN apt-get update && apt-get install \
      gcc libc-dev \
      libxml2-dev libxslt-dev
    
RUN pip install -r /requirements.txt

RUN mkdir /app
WORKDIR /app
COPY ./app /app


