# Generated by Django 2.1.15 on 2020-05-18 03:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200517_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='WhatsApp phone number', max_length=31),
        ),
    ]
