# Generated by Django 3.0.7 on 2020-07-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200718_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
        migrations.AddField(
            model_name='consent',
            name='notification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='core.Notification'),
        ),
    ]
