# Generated by Django 3.0.7 on 2020-07-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consent',
            old_name='netflix_chrome_ext',
            new_name='chrome_ext',
        ),
        migrations.RenameField(
            model_name='consent',
            old_name='netflix_whatsapp',
            new_name='whatsapp',
        ),
        migrations.DeleteModel(
            name='UserApp',
        ),
    ]
